set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g prefix C-s

unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind H resize-pane -L 20
bind L resize-pane -R 20

set-option -g status on

# renumber windows
set-option -g renumber-windows on
set-option -g status-bg colour235

bind g resize-pane -y 5

source-file ~/.tmuxline.conf

# fix colors
set -g default-terminal "screen-256color"

# vi mode
set-window-option -g mode-keys vi

unbind v
bind v paste-buffer

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection

bind c new-window -c "#{pane_current_path}"

set-option -g status-interval 2
set -s escape-time 0

run '~/.tmux/plugins/tpm/tpm'

