set -g prefix C-s
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind H resize-pane -L 40
bind L resize-pane -R 40

set -s escape-time 0
set-option -g status on
set-option -g utf8 on

# renumber windows
set-option -g renumber-windows on
set-option -g status-bg colour235

bind g resize-pane -y 5

##### POWERLINE 2
source $HOME/Library/Python/2.7/lib/python/site-packages/powerline/bindings/tmux/powerline.conf

# fix colors
set -g default-terminal "screen-256color"

# vi mode
set-window-option -g mode-keys vi

unbind v
bind v paste-buffer
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection

bind c new-window -c "#{pane_current_path}"

set-option -g status-interval 1
