# vim:fileencoding=utf-8

include ./theme-hybrid.conf

font_family      FiraCode Nerd Font Mono
font_size 12

modify_font cell_width 90%
modify_font cell_height -2px
modify_font baseline 3

enable_audio_bell no

remember_window_size  yes
window_padding_width 3
hide_window_decorations titlebar-only
